# render.yaml - Sistema FONTES v3.0
services:
  - type: web
    name: fontes-sistema-inss
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements-prod.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true
